version: "1.0"

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
        - MONGO_URI=mongodb://admin:12345@mongodb:27017/test?authSource=test
    depends_on:
        - mongodb

  mongodb:
    build:
      context: ./infrastructure/mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    volumes:
      - mongodb_volume:/data/db


volumes:
  mongodb_volume:



