version: "1.0"

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./infrastructure/mongodb
    ports:
      - "3306:3306"
    volumes:
      - mongoDB_volume:/data/db

volumes:
  mongoDB_volume:



